---
sites:
  test: https://magtest.ncep.noaa.gov
  prod: https://mag.ncep.noaa.gov
  area_from: prod
  cycle_from: test
  products_from: test
  cluster_from: prod
  stations_from: test
  storms_from: test
  order_of_iteration:
  - test
  - prod
  today_only: true

driver: Firefox

headless: false

remote:
  'bstack:options':
    os: "Windows"
    osVersion: "10"
    resolution : "1920x1080"
    projectName : "MAG"
    debug : "true"
  browserName: "Firefox"
  browserVersion: "latest"

plan:
  GFS:
    section: Model Guidance
    model: GFS
    area_count: 2
    product_count: 2
    hour_count: 1
    area: {}
  GEFS-SPAG:
    section: Model Guidance
    model: GEFS-SPAG
    area_count: 1
    product_count: 1
    hour_count: 1
    area: {}
  GEFS-MEAN-SPRD:
    section: Model Guidance
    model: GEFS-MEAN-SPRD
    area_count: 1
    product_count: 3
    hour_count: 1
    area: {}
  NAEFS:
    section: Model Guidance
    model: NAEFS
    area_count: 1
    product_count: 2
    hour_count: 1
    area: {}
  PANELS:
    section: Model Guidance
    model: PANELS
    area_count: 2
    product_count: 2
    hour_count: 1
    area: {}
  NAM:
    section: Model Guidance
    model: NAM
    area_count: 2
    product_count: 2
    hour_count: 1
    area: {}
  NAM-HIRES:
    section: Model Guidance
    model: NAM-HIRES
    area_count: 1
    product_count: 0
    hour_count: 1
    area: {}
  FIREWX:
    section: Model Guidance
    model: FIREWX
    area_count: 0
    product_count: 1
    hour_count: 1
    area: {}
  RAP:
    section: Model Guidance
    model: RAP
    area_count: 1
    product_count: 4
    hour_count: 1
    area: {}
  HRRR:
    section: Model Guidance
    model: HRRR
    area_count: 2
    product_count: 2
    hour_count: 2
    area: {}
  HRW-NMMB:
    section: Model Guidance
    model: HRW-NMMB
    area_count: 3
    product_count: 5
    hour_count: 1
    area: {}
  HRW-ARW:
    section: Model Guidance
    model: HRW-ARW
    area_count: 0
    product_count: 1
    hour_count: 1
    area: {}
  HRW-ARW2:
    section: Model Guidance
    model: HRW-ARW2
    area_count: 1
    product_count: 3
    hour_count: 1
    area: {}
  SREF:
    section: Model Guidance
    model: SREF
    area_count: 1
    product_count: 3
    hour_count: 1
    area: {}
  HREF:
    section: Model Guidance
    model: HREF
    area_count: 0
    product_count: 5
    hour_count: 1
    area: {}
  NBM:
    section: Model Guidance
    model: NBM
    area_count: 1
    product_count: 3
    hour_count: 1
    area: {}
  SREF-CLUSTER:
    section: Model Guidance
    model: SREF-CLUSTER
    area_count: 2
    product_count: 2
    hour_count: 1
    cluster_count: 1
    area: {}
  WW3:
    section: Model Guidance
    model: WW3
    area_count: 1
    product_count: 3
    hour_count: 1
    area: {}
  ESTOFS:
    section: Model Guidance
    model: ESTOFS
    area_count: 0
    product_count: 0
    hour_count: 1
    area: {}
  ICE-DRIFT:
    section: Model Guidance
    model: ICE-DRIFT
    area_count: 1
    product_count: 1
    hour_count: 1
    area: {}
  STORM-TRACKS:
    section: Model Guidance
    model: STORM-TRACKS
    area_count: 2
    product_count: 2
    hour_count: 1
    area: {}
  UAIR:
    section: Observations and Analyses
    model: UAIR
    area_count: 1
    product_count: 1
    area: {}
  SKEWT:
    section: Observations and Analyses
    model: SKEWT
    area_count: 2
    station_count: 2
    area: {}
  RTMA:
    section: Observations and Analyses
    model: RTMA
    area_count: 1
    product_count: 0
    area: {}
  TROP:
    section: Tropical Guidance
    model: TROP
    storm_count: 2
    type_count: 1
    product_count: 2
    hour_count: 1
    storm: {}
  NAM-SND:
    section: Forecast Soundings
    model: NAM-SND
    station_count: 2
    hour_count: 2
    stations: []
  GFS-SND:
    section: Forecast Soundings
    model: GFS-SND
    station_count: 1
    hour_count: 1
    stations: []

delays:
  hover_and_click: 1
  common: 1
  image: 1