---
project_key: MAG
token_file: token.txt

check_today:
  cycle_key: MAG-C1

compare:
  cycle_key: MAG-C2
  folder: "/Image Diffs"

TODAY_TESTCASES:
    'GFS': 'MAG-T2'
    'GEFS-SPAG': 'MAG-T3'
    'NAEFS': 'MAG-T4'
    'NAM': 'MAG-T5'
    'NAM-HIRES': 'MAG-T6'
    'FIREWX': 'MAG-T7'
    'RAP': 'MAG-T8'
    'HRRR': 'MAG-T9'
    'HRW-NMMB': 'MAG-T10'
    'HRW-ARW': 'MAG-T11'
    'HRW-ARW2': 'MAG-T12'
    'SREF': 'MAG-T13'
    'HREF': 'MAG-T14'
    'NBM': 'MAG-T15'
    'SREF-CLUSTER': 'MAG-T16'
    'WW3': 'MAG-T17'
    'ESTOFS': 'MAG-T18'
    'ICE-DRIFT': 'MAG-T19'
    'STORM-TRACKS': 'MAG-T20'
    'UAIR': 'MAG-T21'
    'SKEWT': 'MAG-T22'
    'RTMA': 'MAG-T23'
    'TROP': 'MAG-T24'
    'GFS-SND': 'MAG-T25'
    'NAM-SND': 'MAG-T26'


